In [30]:
data = {
    'date': ['2021-12-01', '01-12-2022', '2022/12/01', '12-01-2021'],
    'country': ['USA', 'U.S.A.', 'America', 'United States'],
    'name': ['Aammar', 'Amaar', 'Hamza', 'Hazma'],
    'sales_2020': [100, 200, None, 200],
    'sales_2021': [None, 150, 300, 150]
}

In [31]:
import pandas as pd

In [32]:
df = pd.DataFrame(data)

In [33]:
df

         date        country    name  sales_2020  sales_2021
0  2021-12-01            USA  Aammar       100.0         NaN
1  01-12-2022         U.S.A.   Amaar       200.0       150.0
2  2022/12/01        America   Hamza         NaN       300.0
3  12-01-2021  United States   Hazma       200.0       150.0

### USING THIS IS VERY IMPORTANT FOR THE DATA TO BE STRUCTURED IN THE SAME FORMAT

In [39]:
# STANDARDIZING THE DATE FORMAT
df['date']=pd.to_datetime(df['date'])

In [40]:
df['date']=df['date'].fillna(df.loc[0,'date'])

In [41]:
# # df['date']= df['date'].fillna(loc[0,'date']) i forgot ot put df.
# df['date'] = df['date'].fillna(df.loc[0, 'date'])  # Go to DataFrame df → row label 0 → column 'date' → give me that value

In [42]:
df

        date        country    name  sales_2020  sales_2021
0 2021-12-01            USA  Aammar       100.0         NaN
1 2021-12-01         U.S.A.   Amaar       200.0       150.0
2 2021-12-01        America   Hamza         NaN       300.0
3 2021-12-01  United States   Hazma       200.0       150.0

In [46]:
df['country']=df['country'].replace({'U.S.A.':'USA','America':'USA','United States':'USA'})

In [47]:
df

        date country    name  sales_2020  sales_2021
0 2021-12-01     USA  Aammar       100.0         NaN
1 2021-12-01     USA   Amaar       200.0       150.0
2 2021-12-01     USA   Hamza         NaN       300.0
3 2021-12-01     USA   Hazma       200.0       150.0

In [48]:
df['name']=df['name'].replace({'Amaar':'Aammar','Hazma':'Hamza'})

In [49]:
df

        date country    name  sales_2020  sales_2021
0 2021-12-01     USA  Aammar       100.0         NaN
1 2021-12-01     USA  Aammar       200.0       150.0
2 2021-12-01     USA   Hamza         NaN       300.0
3 2021-12-01     USA   Hamza       200.0       150.0