In [22]:
data = {
    'date': ['2021-12-01', '01-12-2022', '2022/12/01', '12-01-2021'],
    'country': ['USA', 'U.S.A.', 'America', 'United States'],
    'name': ['Aammar', 'Amaar', 'Hamza', 'Hazma'],
    'sales_2020': [100, 200, None, 200],
    'sales_2021': [None, 150, 300, 150]
}

In [23]:
import pandas as pd

In [24]:
df = pd.DataFrame(data)

In [25]:
df

         date        country    name  sales_2020  sales_2021
0  2021-12-01            USA  Aammar       100.0         NaN
1  01-12-2022         U.S.A.   Amaar       200.0       150.0
2  2022/12/01        America   Hamza         NaN       300.0
3  12-01-2021  United States   Hazma       200.0       150.0

### USING THIS IS VERY IMPORTANT FOR THE DATA TO BE STRUCTURED IN THE SAME FORMAT

In [26]:
# standardizing the date format
df['date'] = pd.to_datetime(df['date'], errors='coerce')
df['date'] = df['date'].dt.strftime('%Y-%m-%d')
df.head()
# df['date'] → .dt → .strftime('%Y-%m-%d')
#  column       ↓           ↓
#            datetime    format dates
#            accessor

         date        country    name  sales_2020  sales_2021
0  2021-12-01            USA  Aammar       100.0         NaN
1         NaN         U.S.A.   Amaar       200.0       150.0
2         NaN        America   Hamza         NaN       300.0
3         NaN  United States   Hazma       200.0       150.0

In [27]:
df['date']=df['date'].fillna(df.loc[0,'date'])

In [28]:
# # df['date']= df['date'].fillna(loc[0,'date']) i forgot ot put df.
# df['date'] = df['date'].fillna(df.loc[0, 'date'])  # Go to DataFrame df → row label 0 → column 'date' → give me that value

In [29]:
df

         date        country    name  sales_2020  sales_2021
0  2021-12-01            USA  Aammar       100.0         NaN
1  2021-12-01         U.S.A.   Amaar       200.0       150.0
2  2021-12-01        America   Hamza         NaN       300.0
3  2021-12-01  United States   Hazma       200.0       150.0