# DATA MERGE SIDE BY SIDE

In [1]:
import pandas as pd

# Example datasets for data merging
# Dataset 1: Pakistani Individuals
data1 = {
    'id': [1, 2, 3],
    'name': ['Ahmed', 'Fatima', 'Ali'],
    'age': [28, 32, 24]
}
df1 = pd.DataFrame(data1)
df1.head()

   id    name  age
0   1   Ahmed   28
1   2  Fatima   32
2   3     Ali   24

In [2]:
# Dataset 2: Additional Information
data2 = {
    'id': [1, 2, 3],
    'city': ['Karachi', 'Lahore', 'Islamabad'],
    'occupation': ['Engineer', 'Doctor', 'Teacher']
}
df2 = pd.DataFrame(data2)
df2.head()

   id       city occupation
0   1    Karachi   Engineer
1   2     Lahore     Doctor
2   3  Islamabad    Teacher

WE WILL USE A PANDAS FUNCION

In [4]:
data3 = pd.merge(df1,df2)
data3

   id    name  age       city occupation
0   1   Ahmed   28    Karachi   Engineer
1   2  Fatima   32     Lahore     Doctor
2   3     Ali   24  Islamabad    Teacher

In [ ]:
# merged_df = pd.merge(df1, df2, on='id', how='inner')
# # syntax to esa hi hai pd.merge( name the dataframes jo bhi hai one,two,three,,.... and , on'uniquie',how'inner'inner is deafult)
# merged_df.head()

# DATA CONCATENATION