# DATA MERGE SIDE BY SIDE

In [12]:
import pandas as pd

# Example datasets for data merging
# Dataset 1: Pakistani Individuals
data1 = {
    'id': [1, 2, 3],
    'name': ['Ahmed', 'Fatima', 'Ali'],
    'age': [28, 32, 24]
}
df1 = pd.DataFrame(data1)
df1.head()

   id    name  age
0   1   Ahmed   28
1   2  Fatima   32
2   3     Ali   24

In [13]:
# Dataset 2: Additional Information
data2 = {
    'id': [1, 2, 3],
    'city': ['Karachi', 'Lahore', 'Islamabad'],
    'occupation': ['Engineer', 'Doctor', 'Teacher']
}
df2 = pd.DataFrame(data2)
df2.head()

   id       city occupation
0   1    Karachi   Engineer
1   2     Lahore     Doctor
2   3  Islamabad    Teacher

WE WILL USE A PANDAS FUNCION

In [14]:
data3 = pd.merge(df1,df2)
data3

   id    name  age       city occupation
0   1   Ahmed   28    Karachi   Engineer
1   2  Fatima   32     Lahore     Doctor
2   3     Ali   24  Islamabad    Teacher

In [15]:
# merged_df = pd.merge(df1, df2, on='id', how='inner')
# # syntax to esa hi hai pd.merge( name the dataframes jo bhi hai one,two,three,,.... and , on'uniquie',how'inner'inner is deafult)
# merged_df.head()

# DATA CONCATENATION

In [16]:
import pandas as pd

# Example datasets for Pakistani context
# Dataset 1 - Pakistani Names and Ages
data1 = {'Name': ['Ahmed', 'Fatima', 'Ali'], 'Age': [28, 32, 24]}
# Dataset 2 - More Pakistani Names and Ages
data2 = {'Name': ['Sara', 'Usman', 'Aisha'], 'Age': [29, 35, 27]}
# Dataset 3 - Cities and Provinces in Pakistan
data3 = {'City': ['Karachi', 'Lahore', 'Islamabad'], 'Province': ['Sindh', 'Punjab', 'Islamabad']}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)
df3 = pd.DataFrame(data3)
print(df1)
print(df2)
print(df3)

     Name  Age
0   Ahmed   28
1  Fatima   32
2     Ali   24
    Name  Age
0   Sara   29
1  Usman   35
2  Aisha   27
        City   Province
0    Karachi      Sindh
1     Lahore     Punjab
2  Islamabad  Islamabad

In [ ]:
# concat_rows = pd.concat([df1,df3]) # axis 0 
concat_rows = pd.concat([df1,df3],axis=0)
concat_rows

     Name   Age       City   Province
0   Ahmed  28.0        NaN        NaN
1  Fatima  32.0        NaN        NaN
2     Ali  24.0        NaN        NaN
0     NaN   NaN    Karachi      Sindh
1     NaN   NaN     Lahore     Punjab
2     NaN   NaN  Islamabad  Islamabad

In [20]:
concat_coloumns = pd.concat([df1,df3],axis=1)
concat_coloumns

     Name  Age       City   Province
0   Ahmed   28    Karachi      Sindh
1  Fatima   32     Lahore     Punjab
2     Ali   24  Islamabad  Islamabad